/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc;

import java.sql.DriverManager;
import java.sql.SQLException;


public class App2 {


    public static void main(String[] args) throws SQLException {

        try (var conn = DriverManager.getConnection("jdbc:h2:mem:hexlet_test")) {


            var sql = "CREATE TABLE users (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255), phone VARCHAR(255))";
            try (var statement = conn.createStatement()) {
                statement.execute(sql);
            }

            User user1 = new User("Serge", "9518000939");
            User user2 = new User("Taty", "9048191086");
            User user3 = new User("Johnny", "3519001086");

            UserDAO dao = new UserDAO(conn);

            dao.save(user1);
            dao.save(user2);
            dao.save(user3);

            System.out.println(dao.find(1L).orElse(null));

            var sql3 = "SELECT * FROM users";
            try (var statement3 = conn.createStatement()) {
                var resultSet = statement3.executeQuery(sql3);
                while (resultSet.next()) {
                    System.out.println(resultSet.getString("username"));
                    System.out.println(resultSet.getString("phone"));
                }
            }
        }
    }
}
